import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TsukiPlay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${fredoka.variable}`}>
      <body>{children}</body>
    </html>
  );
}
